### ISSUE TITLE
Input/Output options broke

### ISSUE THREAD

**Issue by dodontommy** [guard/guard-haml-coffee#2]
Before the pull request was merged into this gem and it was moved to this repository, the input and output options were working.

I am now receiving both `Failed to call Guard::HamlCoffee.new(options): Unknown option: :output` and `Failed to call Guard::HamlCoffee.new(options): Unknown option: :input` upon trying to run `guard init` with these options in place.

I see that `input` and `output` options are no longer in the `valid_options` dictionary, possible merge issue?

**Comment by e2** [comment]
Fix released in 1.0.2

(I've added unit tests for this, so it shouldn't break in the future).
